#+TITLE: Sitemap for project blog

- [[file:index.org][The Blog]]
- [[file:blog/Coeffects.org][Коэффекты]] :: Коэффекты - очень размытое понятие, используемое в разных контекстах немного
  по-разному. Но для построения чисто функционального приложения они являются
  очень важными. Попробую обьяснить, как я их понимаю сам.
- [[file:blog/Comments.org][Комментарии в коде]] :: Устаревание комментариев в коде - проблема, для которой, на первый взгляд, не
  найти хорошего решения. Попробую накидать свои мысли об этом.
- [[file:blog/Di-frameworks.org][Решают ли DI-фреймворки больше проблем, чем создают?]] :: В моём канале с мемами много шуток про то, что в спорах между Dagger 2 и Koin на
  самом деле побеждают фабрики. Так вот, это не шутки. Я считаю что DI-фреймворки
  в android - это подражание спрингерам, дань моде, следствие хронического
  ООП-клинкода головного мозга и просто переоценённое излишество. Жёсткий наброс
  вкинут, давайте разбираться, правда ли это.
- [[file:blog/Online-meetups.org][Кому нужны онлайн митапы?]] :: Провести митап онлайн гораздо дешевле чем снимать помещение и кормить всех
  пиццулей. На мой взгляд это путь в никуда, а сам я всегда стараюсь
  организовывать митапы оффлайн. Рассказываю, почему.
- [[file:blog/DSL-over-API.org][Антипаттерн DSL over API]] :: Kotlin часто рекламируется как язык, в котором классно и легко писать eDSL -
  embedded domain specific languages. Писать-то может их и классно, но часто потом
  пользоваться получившимися DSL не очень удобно. В чём же проблема?
- [[file:blog/Data-oriented-programming.org][Data Oriented Programming]] :: Мой обзор на MEAP книги Data Oriented Programming. Неплохая книжечка, в которой
  описаны все плюсы clojure, но о самом языке ни слова.