version: 2.1
jobs:
  build_site:
    working_directory: "/srv/jekyll"
    docker:
      - image: jekyll/jekyll:4.0.0
    steps:
      - checkout
      - restore_cache:
          key: rubygems-v2-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install dependencies
          command: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: rubygems-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Build site
          command: jekyll build
      - run:
          name: Disable Jekyll on GH Pages
          command: touch _site/.nojekyll
      - persist_to_workspace:
          root: .
          paths:
              - _site
  site-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@mishkun"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - '2e:93:83:b5:06:c0:8d:8d:74:ab:96:24:30:04:20:97'
      - run:
          name: Deploy slides to gh-pages branch
          command: gh-pages --dist _site
workflows:
  version: 2
  build_deploy:
    jobs:
      - build_site:
          filters:
            branches:
              ignore: gh-pages
      - site-deploy:
          requires:
            - build_site
          filters:
            branches:
              only: master
