# -*- coding: utf-8 -*-
#+TITLE: Кому нужны онлайн митапы?
#+Date: 11-12-2021

#+begin_abstract
Провести митап онлайн гораздо дешевле чем снимать помещение и кормить всех
пиццулей. На мой взгляд это путь в никуда, а сам я всегда стараюсь
организовывать митапы оффлайн. Рассказываю, почему.
#+end_abstract

* Онлайн митапы были временным решением
Кажется, что прошло уже почти 2 года с начала ковидопокалипсиса. Сразу попрошу
прощения у организаторов любых движух в онлайне за резкий тон. Вы большие
молодцы и организация конф и докладов - тяжелая работа, зачастую воспринимаемая
участниками как должное. Но настало время признать, что онлайн митапы в формате
"говорящая голова читает текст под слайды" были простительны только для
организаторов сезона весна-лето 2020, которых новая ковидная реальность застала
врасплох. Сейчас, когда уже всем понятно, что мир изменился, нужно придумывать
что-то другое, но мы упорно держимся за старый формат, пытаясь сохранить его,
как мумию Ленина в Мавзолее.
* Онлайн трансляции митапов - это шиза
Ты сидишь перед монитором и смотришь, как докладчик что-то рассказывает, время
от времени становясь то более резким, то более размытым пока счётчик качества
скочит от 480p до 720p. В чате за весь митап три сообщения. И все три –
"Задавайте вопрос спикеру и мы ответим на него онлайн!". Да и откуда им взяться,
если счётчик просмотров явно говорит, что вечером вторника желающих слушать про
разработку немного. Ловишь себя на мысли, а реальные ли те 20 зрителей.
Пытаешься понять, не дипфейк ли докладчик. Отвлекся на звуки из соседней комнаты –
твои домашние смотрят там что-то веселое, судя по громкому смеху. Вспоминаешь,
что забыл поужинать. Ставишь доклад на паузу, идёшь быстренько что-то разогреть.
Возвращаешься – ставишь на 2х, ведь ты хотел задать вопрос спикеру в конце. В
какой-то момент думаешь: "а может потом всё на 2х и посмотреть? А сейчас лучше
повтыкаю в новый сериальчик". Закрываешь вкладку, идёшь к домашним смотреть
сериал. С вероятностью 99% доклад ты так и не досмотришь больше никогда. А
стоило ли начинать?
* Просмотр в записи - это нормально
Другое дело, когда тебя дйствительно интересует какая-то тема и ты ищешь видео
по ней. Не важно, с онлайн или оффлайн мероприятия. Находишь, смотришь на 2х,
3х, 0.5х. Смотришь на рабочем месте, в зале, в туалете, в транспорте, за ужином
– когда тебе удобно и как тебе удобно. Или не смотришь, а прокликиваешь и
понимаешь, что оно не про то что ты хотел.
* Социальные трансляции прошлого
Я не говорю, что всё надо смотреть только в записи. Даже до ковида были
интересные трансляции. Но обычно это были большие события типа WWDC или Google
I/O и мы собирались со знакомыми в баре и смотрели keynote доклады все вместе,
играли в буллшит бинго, реагировали на крутые анонсы криками "да лааадно?!".
Если трансляцию не смотрят люди, которых ты считаешь частью своей социальной
группы, то она сразу теряет 1000 очков. Я припоминаю как было классно когда
прикупили корпоративный онлайн билет на конфу, съехались все вместе, забились в
переговорку и смотрели, обсуждали. А сейчас билет был только у меня и я не видел
ни одного доклада онлайн. Да и не поделишься интересным видосом с другом без
дилеммы "нарушение правил площадки или ХХ килорублей за один видосик".
* Конференции уже не те
Крупные площадки "старого мира" сейчас играют не на своём поле и живы(?) только
благодаря бренду и опыту. Но при этом не могут резко изменить свой формат,
потому что этот самый бренд его и диктует. Но бренд требует формат "старого
оффлайна". А он на онлайн не ложится. Когда то видосы с конференций были
побочным продуктом, как пакетик мерча или фотки в инсте участников. Сейчас это
стало основным продуктом и это уже не то. Бренд изменяет себе.
* Оффлайн тоже не надёжный выход
Многие требуют возврата в оффлайн, но получится ли с ковидными ограничениями
собрать достаточно людей, чтобы оплатить аренду и продакшен? Я не знаю. Но я
чувствую, что сейчас это не работает и нужно что то менять.
* HR-бренд удалённо плохо качается
Для организации митапов, спонсируемых компаниями для hr-бренда, вообще не вижу
никакого смысла в онлайн докладах. Да, это может быть бюджетнее чем арендовать
помещение, нанимать кейтеринг и делать ещё целую кучу вещей. Но без чувства
общности, без социального взаимодействия лояльность hr-бренду растёт туго. А
доклады можно отснять и выложить позже. Всё равно большинство просмотров
собирают записи, а не трансляция, если обязательно нужно какие-то метрики
считать.
* TL;DR:
Старый формат одиночного доклада чужд онлайну. Нужно либо придумывать что-то
кардинально новое либо признавать поражение и возвращаться в оффлайн.
